base_model_name: C:\Users\Admin\Projects\saved_models\bert_base_uncased
embedding_model_name: C:\Users\Admin\Projects\saved_models\bert_base_uncased
freq_file: info/train_freqs_sst.json
importance_corpus: C:\Users\Admin\Projects\datasets\sst2\clean_data
importance_file: info/word_positivities_sst.json
importance_model: lr
importance_model_params: {}
importance_word_min_freq: 0
keyword_freq: 0
keyword_score: 0
keywords: cf
label: 0
model_type: bert
n_target_words: 10
seed: 0
task: sst-2
tgt_dir: C:\Users\Admin\Projects\saved_models\bert_sst2\pretrained_weights
use_keywords_as_target: false
vectorizer: tfidf
vectorizer_params: {}
